### PR TITLE
Practical Task №1.1 Markdown & Git

### PR DESCRIPTION
**Pull request by leeshko**

### CODE REVIEW

**Comment by nadejdashed** [comment]
Please be careful with Task requirements. One of them was "Commit names according to the guideline".
It's no so critical now but it will be critical on a project. Every project has their own styleguide and processes, and every developer should follow them. Commit name is one guide that should be followed.

**Comment by nadejdashed** [comment]
Also one other requirement - "PR name should contain the task name and probably additional info."

**Comment by nadejdashed** [comment]
Let's add few features of Markdown:
- <fake@example.com>
- every point under different heading

**Comment by leeshko** [comment]
everything was fixed

**Pull request closed without merging**
